name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          args: --exclude=Assignment1/
      - name: API Keys in Github Secrets
        env:
          FLIGHT_API_KEY: ${{ secrets.FLIGHT_API_KEY }}
          TICKET_API_KEY: ${{ secrets.TICKETS_API_KEY }}